// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"time"
)

type DetailPesanan struct {
	PesananID int32 `json:"pesanan_id"`
	MenuID    int32 `json:"menu_id"`
	Harga     int32 `json:"harga"`
	Jumlah    int32 `json:"jumlah"`
}

type Kategori struct {
	ID       int32  `json:"id"`
	Kategori string `json:"kategori"`
}

type Meja struct {
	Nomor      int32     `json:"nomor"`
	DibuatPada time.Time `json:"dibuat_pada"`
}

type Menu struct {
	ID         int32  `json:"id"`
	KategoriID int32  `json:"kategori_id"`
	Menu       string `json:"menu"`
	Deskripsi  string `json:"deskripsi"`
	Foto       string `json:"foto"`
	Tersedia   bool   `json:"tersedia"`
	Harga      int32  `json:"harga"`
}

type Pembayaran struct {
	ID          int32     `json:"id"`
	PesananID   int32     `json:"pesanan_id"`
	Bayar       int32     `json:"bayar"`
	DibayarPada time.Time `json:"dibayar_pada"`
}

type Pesanan struct {
	ID          int32     `json:"id"`
	Kode        string    `json:"kode"`
	MejaNomor   int32     `json:"meja_nomor"`
	DipesanPada time.Time `json:"dipesan_pada"`
}
