// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package postgres

import (
	"context"
)

const createMeja = `-- name: CreateMeja :exec
INSERT INTO meja (nomor, dibuat_pada) VALUES ($1, DEFAULT)
`

func (q *Queries) CreateMeja(ctx context.Context, nomor int32) error {
	_, err := q.db.ExecContext(ctx, createMeja, nomor)
	return err
}
