// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package database

import (
	"context"
)

const createMeja = `-- name: CreateMeja :exec
INSERT INTO meja (nomor) VALUES ($1)
`

func (q *Queries) CreateMeja(ctx context.Context, nomor int32) error {
	_, err := q.db.ExecContext(ctx, createMeja, nomor)
	return err
}
